#!/usr/bin/env bash
#
# test-seed-scrub.sh — functional test for files/usr/lib/rasputin/scrub-seed-token.
#
# WHY A FUNCTIONAL TEST AND NOT JUST `bash -n`
#   validate-files.sh checks syntax, executable modes and structure. None of
#   those can see that a script blanked the wrong line, ate the operator's SSH
#   key, or wrote nothing at all. This one mutates a filesystem during
#   first-boot provisioning, where uci-defaults self-delete on exit 0 and there
#   is no second chance — the exact failure shape validate-files.sh's own header
#   warns about. geekdojo/geekdojo-brain#130, and a first bite out of #147.
#
# THREE TIERS, because they prove different things:
#   1. content   — the transformation, against a plain directory. Runs anywhere,
#                  including a developer Mac.
#   2. vfat      — the same assertions against a REAL FAT filesystem, which is
#                  what the seed partition actually is. Needs mkfs.vfat + a loop
#                  mount, so it needs Linux and privileges.
#   3. discovery — the NO-ARGUMENT path: locate the partition by label, mount it
#                  read-write, scrub, unmount. This is the code that runs on
#                  hardware, and tier 1 does not touch it. Uses a stub `block`
#                  on PATH, which is legitimate because seed-fat-device resolves
#                  `block` through PATH exactly as OpenWrt does.
#
#   Tiers 2 and 3 SKIP where they cannot run rather than failing a Mac. Set
#   REQUIRE_FAT=1 (CI does) to turn a skip into a failure — a test that quietly
#   stops testing in the one environment that could run it is worse than absent.
#
# The script under test is /bin/sh on the target (busybox ash), so it is invoked
# through `sh` here — dash on a CI runner, which is a closer approximation than
# bash. Not identical to ash; the bench run is what closes that gap.
#
# Usage: ./scripts/test-seed-scrub.sh
set -uo pipefail

cd "$(dirname "$0")/.." || exit 2
SCRUB="$PWD/files/usr/lib/rasputin/scrub-seed-token"
LOOKUP="$PWD/files/usr/lib/rasputin/seed-fat-device"
TOKEN_KEY=RASPUTIN_CP_JOIN_TOKEN

fail=0
pass=0
ok()   { printf '  ✓ %s\n' "$*"; pass=$((pass + 1)); }
bad()  { printf '  ✗ %s\n' "$*" >&2; fail=$((fail + 1)); }
note() { printf '  %s\n' "$*"; }

# A seed shaped like the real thing: the Add-node wizard's fields, a comment,
# an ed25519 key whose base64 carries the `/` and `+` that would break a
# careless sed delimiter, and a value containing `#` for the same reason.
write_seed() {
	cat > "$1" <<'SEED'
# Rasputin enrollment seed — generated by Add node
RASPUTIN_NODE_ROLE=firewall
RASPUTIN_NODE_ID=fw-n100-0001
RASPUTIN_CLUSTER_ID=e3bench
RASPUTIN_NATS_URL=nats://e3bench.local:4222
RASPUTIN_CP_JOIN_TOKEN=b7c1d9e4f2a05386c4d1e8f70a2b6c9d3e5f8a1b4c7d0e2f5a8b1c4d7e0f3a6b
RASPUTIN_SSH_AUTHORIZED_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH+w/Kf3Zq1s+RtY/8xNbVd0PqL9mE4jX2cW7uT/kR6a operator@mac
RASPUTIN_NTP_SERVER=pool.ntp.org
RASPUTIN_RELEASE_CHANNEL=dev#stable-later
SEED
}

# assert_scrubbed: the token's value is gone, and every OTHER line survived
# byte for byte. The second half is the one that matters — a scrub that also
# ate the SSH key would strand the operator with no way back into the box.
assert_scrubbed() {
	local f="$1" label="$2" before="$3"

	if grep -q "^${TOKEN_KEY}=$" "$f"; then
		ok "$label: token blanked, key retained"
	else
		bad "$label: expected a bare '${TOKEN_KEY}=' line, got: $(grep "^${TOKEN_KEY}=" "$f" || echo '<no token line>')"
	fi
	if grep -q "^${TOKEN_KEY}=." "$f"; then
		bad "$label: a token VALUE is still present"
	fi

	local diff_out
	diff_out=$(diff <(grep -v "^${TOKEN_KEY}=" "$before") <(grep -v "^${TOKEN_KEY}=" "$f") 2>&1)
	if [ -z "$diff_out" ]; then
		ok "$label: every other line byte-identical"
	else
		bad "$label: non-token lines changed:"
		printf '%s\n' "$diff_out" | sed 's/^/      /' >&2
	fi
}

run_scrub() { sh "$SCRUB" "$@" >/dev/null 2>&1; }

# ---------------------------------------------------------------- tier 1
echo "1. Content transformation (portable)"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# --- the ordinary case
d="$TMP/plain"; mkdir -p "$d"
write_seed "$d/seed.env"
cp "$d/seed.env" "$TMP/before.env"
run_scrub "$d"
rc=$?
[ $rc -eq 0 ] && ok "exits 0" || bad "exit code $rc"
assert_scrubbed "$d/seed.env" "seed.env" "$TMP/before.env"

# --- idempotence: provisioning can be re-run; a second scrub must be a no-op
cp "$d/seed.env" "$TMP/once.env"
run_scrub "$d"
if diff -q "$TMP/once.env" "$d/seed.env" >/dev/null; then
	ok "second run changes nothing"
else
	bad "not idempotent"
fi

# --- both accepted names present: 98 stages the first it finds, so the other
#     must not be left holding a live token
d="$TMP/both"; mkdir -p "$d"
write_seed "$d/rasputin-seed.env"
write_seed "$d/seed.env"
run_scrub "$d"
if grep -q "^${TOKEN_KEY}=." "$d/rasputin-seed.env" || grep -q "^${TOKEN_KEY}=." "$d/seed.env"; then
	bad "a token survived when both seed names were present"
else
	ok "both seed filenames scrubbed"
fi

# --- nothing to do cases: these must be silent successes, never errors
d="$TMP/empty"; mkdir -p "$d"
run_scrub "$d" && ok "no seed file: exits 0" || bad "no seed file: non-zero exit"

d="$TMP/blank"; mkdir -p "$d"
printf 'RASPUTIN_NODE_ROLE=firewall\n%s=\n' "$TOKEN_KEY" > "$d/seed.env"
cp "$d/seed.env" "$TMP/blank-before.env"
run_scrub "$d"
if diff -q "$TMP/blank-before.env" "$d/seed.env" >/dev/null; then
	ok "already-blank token: file untouched"
else
	bad "already-blank token: file was rewritten"
fi

d="$TMP/notoken"; mkdir -p "$d"
printf 'RASPUTIN_NODE_ROLE=firewall\nRASPUTIN_NODE_ID=x\n' > "$d/seed.env"
cp "$d/seed.env" "$TMP/notoken-before.env"
run_scrub "$d"
if diff -q "$TMP/notoken-before.env" "$d/seed.env" >/dev/null; then
	ok "no token line: file untouched"
else
	bad "no token line: file was rewritten"
fi

run_scrub "$TMP/does-not-exist" && ok "absent directory: exits 0" || bad "absent directory: non-zero exit"

# --- a seed written on Windows or macOS and dropped on the FAT
d="$TMP/crlf"; mkdir -p "$d"
printf 'RASPUTIN_NODE_ROLE=firewall\r\n%s=deadbeef\r\nRASPUTIN_NODE_ID=fw-1\r\n' "$TOKEN_KEY" > "$d/seed.env"
run_scrub "$d"
if grep -q "^${TOKEN_KEY}=." "$d/seed.env"; then
	bad "CRLF seed: token value survived"
else
	ok "CRLF seed: token blanked"
fi
if [ "$(tr -d '\n' < "$d/seed.env" | tr -cd '\r' | wc -c | tr -d ' ')" -eq 2 ]; then
	ok "CRLF seed: other lines keep their line endings"
else
	bad "CRLF seed: line endings on other lines were altered"
fi

# ---------------------------------------------------------------- tiers 2+3
echo
echo "2. Real vfat + 3. label discovery and mount"
if [ "$(uname -s)" != "Linux" ]; then
	note "SKIPPED — needs Linux (loop mount). Ran on $(uname -s)."
	skipped=1
elif ! command -v mkfs.vfat >/dev/null 2>&1; then
	note "SKIPPED — mkfs.vfat not installed (dosfstools)."
	skipped=1
elif [ "$(id -u)" -ne 0 ] && ! sudo -n true 2>/dev/null; then
	note "SKIPPED — needs root or passwordless sudo for the loop mount."
	skipped=1
else
	skipped=0
	SUDO=""; [ "$(id -u)" -eq 0 ] || SUDO="sudo"
	IMG="$TMP/seed.img"; MNT="$TMP/mnt"; mkdir -p "$MNT"
	dd if=/dev/zero of="$IMG" bs=1M count=8 status=none
	mkfs.vfat -n RASPUTIN-FW "$IMG" >/dev/null

	LOOP=$($SUDO losetup --find --show "$IMG")
	$SUDO mount -t vfat -o rw,umask=000 "$LOOP" "$MNT"
	write_seed "$MNT/seed.env"
	cp "$MNT/seed.env" "$TMP/fat-before.env"

	# tier 2 — the transformation, on the filesystem it really runs against
	run_scrub "$MNT"
	assert_scrubbed "$MNT/seed.env" "vfat" "$TMP/fat-before.env"

	# tier 3 — the no-argument path: discover by label, mount rw, scrub, unmount
	write_seed "$MNT/seed.env"
	$SUDO umount "$MNT"

	STUB="$TMP/bin"; mkdir -p "$STUB"
	# `block info` output shaped like OpenWrt's, including a decoy partition so
	# the label match has to actually discriminate.
	cat > "$STUB/block" <<STUBEOF
#!/bin/sh
[ "\$1" = "info" ] || exit 0
echo '/dev/sda1: UUID="1234-ABCD" LABEL="RASPUTINEFI" VERSION="FAT32" TYPE="vfat"'
echo '$LOOP: UUID="5678-EF01" LABEL="RASPUTIN-FW" VERSION="FAT32" TYPE="vfat"'
STUBEOF
	chmod +x "$STUB/block"

	if [ "$(PATH="$STUB:$PATH" sh "$LOOKUP")" = "$LOOP" ]; then
		ok "discovery: seed-fat-device picks RASPUTIN-FW over RASPUTINEFI"
	else
		bad "discovery: got '$(PATH="$STUB:$PATH" sh "$LOOKUP")', want $LOOP"
	fi

	# The helper calls /usr/lib/rasputin/seed-fat-device by absolute path, which
	# is what runs on the box — so install both there for this tier.
	$SUDO mkdir -p /usr/lib/rasputin
	$SUDO cp "$LOOKUP" "$SCRUB" /usr/lib/rasputin/
	$SUDO chmod +x /usr/lib/rasputin/seed-fat-device /usr/lib/rasputin/scrub-seed-token

	$SUDO env PATH="$STUB:$PATH" sh /usr/lib/rasputin/scrub-seed-token >/dev/null 2>&1
	rc=$?
	[ $rc -eq 0 ] && ok "no-argument path: exits 0" || bad "no-argument path: exit $rc"

	if mountpoint -q "$MNT" 2>/dev/null; then
		bad "no-argument path: left the seed FAT mounted"
	else
		ok "no-argument path: unmounted cleanly"
	fi

	$SUDO mount -t vfat -o rw,umask=000 "$LOOP" "$MNT"
	assert_scrubbed "$MNT/seed.env" "no-argument path" "$TMP/fat-before.env"
	$SUDO umount "$MNT"
	$SUDO losetup -d "$LOOP"
fi

if [ "${skipped:-0}" -eq 1 ] && [ "${REQUIRE_FAT:-0}" = "1" ]; then
	bad "REQUIRE_FAT=1 but the vfat tiers did not run — this is the environment that was supposed to run them"
fi

echo
if [ "$fail" -eq 0 ]; then
	echo "seed-scrub: $pass check(s) passed"
	exit 0
fi
echo "seed-scrub: $fail check(s) FAILED, $pass passed" >&2
exit 1
